[book]
authors = ["Antonio Garcia-Dominguez"]
language = "en"
multilingual = false
src = "src"
title = "Engineering 2 Practicals"
[output.html]
additional-js = ["custom-languages/eol.js", "custom-languages/evl.js", "custom-languages/etl.js", "custom-languages/egx.js", "custom-languages/egl.js","custom-languages/init.js"]